[package]
name = "tokio-uring-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-uring = { workspace = true }
config = { path = "../config" }
core_affinity = "0.7.6"